### ISSUE TITLE
/vt/ and /e/ archive domain.

### ISSUE THREAD

**Issue by a-person-oops** [space-nuko/sd-webui-utilities#1]
https://archive.palanq.win/ has an api as it's running FoolFuuka :)
Thanks for adding all the domains btw! Love ya <3

Could you possibly add a way to continuously monitor the latest threads?
Not sure logistically how that'd work but if it's possible that'd be awesome :)

**Comment by a-person-oops** [comment]
Another request for the script is to remove the first 65 characters of the 8chan files it downloads due to the incredibly long file names.


Also broke it due to Japanese filename I guess
```
  File "C:\user\user\pyenv-win\versions\3.11.0\Lib\multiprocessing\pool.py", line 873, in next
    raise value
  File "C:\user\user\pyenv-win\versions\3.11.0\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "Z:\Archive\hdg_archive.py", line 671, in worker
    basepath, url, real_name, mtime = t
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\Archive\hdg_archive.py", line 653, in save_link
    try:

OSError: [Errno 22] Invalid argument: 'Z:\\Archive\\archive.palanq\\vt\\38484785\\1670326786306_【新衣装】マジシャン？アリス？魔法少女？？このシルエットは？！【ホロライブ-大神ミオ】_ 【新衣装】マジシャン？アリス？魔法少女？？このシルエットは？！【ホロライブ-大神ミオ.png'
```

**Comment by space-nuko** [comment]
/vt/ can be archived right now, kind of, because I scrape warosu.org. I hadn't thought about /e/ though, I'll have to test on that one

To "monitor" all the threads I use the recently added `-n` flag with `hdg_archive.py` to scrape the last N threads. So for 4 threads you add `-n4`. Then I run that in a loop for all the boards I want to archive every half hour or so.

**Comment by space-nuko** [comment]
And thanks for the palanq.win link btw, had no idea that existed

**Comment by a-person-oops** [comment]
> And thanks for the palanq.win link btw, had no idea that existed

No problem! Really appreciate your script :)
Glad I could tell you about it :)

**Comment by a-person-oops** [comment]
Is there any chance you could add an option to sanitize the file names to exclude emojis/non utf8 characters?
Some photo indexing software can't handle emojis in filenames :/

**Comment by space-nuko** [comment]
So I managed to add support for /e/ but it seems like FoolFuuka is ignoring me when I pass it the `?board=e` parameter, even though `&text=voldy` works fine. So I just skip any posts that don't match the passed board. According to [this](https://foolfuuka.readthedocs.io/en/latest/code_guide/documentation/api.html) it's supposed to be the board shortname. Would you have any information about this, am I doing it wrong?

> Is there any chance you could add an option to sanitize the file names to exclude emojis/non utf8 characters?

Yeah I can do that.

**Comment by a-person-oops** [comment]
> So I managed to add support for /e/ but it seems like FoolFuuka is ignoring me when I pass it the `?board=e` parameter, even though `&text=voldy` works fine. So I just skip any posts that don't match the passed board. According to [this](https://foolfuuka.readthedocs.io/en/latest/code_guide/documentation/api.html) it's supposed to be the board shortname. Would you have any information about this, am I doing it wrong?
> 
> > Is there any chance you could add an option to sanitize the file names to exclude emojis/non utf8 characters?
> 
> Yeah I can do that.

It's because their recent posts don't actually have "voldy" in it at all lmfao.
I was using the https://rentry.org/sdmodels url as the search term. Going way back on the archive to find the possible text in the threads also led me to seeing that they didn't include voldy but linked to other github repos

**Comment by a-person-oops** [comment]
do you know why this isn't working on my linux install? @space-nuko 

What version of Python are you on? I'm getting this error on Python 3.10.6 on Pop!_OS 22.04 LTS

```Saving: \mnt\sd\Archive\archiveofsins\h\7185614\1676419900217452_look how hard i can cum.png
Saving: \mnt\sd\Archive\archiveofsins\h\7185614\1676419989324428_03984-778644185-15_Feb_2023-d5f8393fea.png
Saving: \mnt\sd\Archive\archiveofsins\h\7185614\catbox\4btpon.png
Saving: \mnt\sd\Archive\archiveofsins\h\7185614\1676420235241543_tally test.jpg
Traceback (most recent call last):
  File "/mnt/sd/Archive/#sd-webui-utilities/hdg_archive.py", line 759, in <module>
    for res in p.imap_unordered(worker, links):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/sd/Archive/#sd-webui-utilities/hdg_archive.py", line 713, in worker
    save_link(basepath, url, real_name, mtime)
  File "/mnt/sd/Archive/#sd-webui-utilities/hdg_archive.py", line 691, in save_link
    os.makedirs(os.path.dirname(path), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by space-nuko** [comment]
Almost certainly because of this fn:

https://github.com/space-nuko/sd-webui-utilities/blob/fbce11d401600ba0beb5639e6d9f77915aa0a5b7/hdg_archive.py#L660-L668

because it sanitizes filepaths based on Windows formatting

I think I'll need a better filepath sanitize function if Linux is being used

My python version is `3.10.8`

**Comment by a-person-oops** [comment]
What OS are you running? Windows? Do you think you could possibly throw together a quick fix for Linux? @space-nuko

**Comment by space-nuko** [comment]
Yeah I run Windows only right now so I can't test unfortunately, I can just spitball things until they work for you maybe

**Comment by space-nuko** [comment]
Could you try https://github.com/space-nuko/sd-webui-utilities/commit/30c2341ef241f140ac77cf002d2d1e90a4a2619a maybe? Made it so it should sanitize Linux pathnames correctly

**Comment by a-person-oops** [comment]
> Could you try [30c2341](https://github.com/space-nuko/sd-webui-utilities/commit/30c2341ef241f140ac77cf002d2d1e90a4a2619a) maybe? Made it so it should sanitize Linux pathnames correctly

That worked!
Thanks!

**Comment by a-person-oops** [comment]
Do you think you could also add the creation date to when the photo was posted? Not just the date modified?

**Comment by space-nuko** [comment]
I already set the date modified on the downloaded files to the time the post was uploaded on *chan, is that what you mean?

**Comment by a-person-oops** [comment]
> I already set the date modified on the downloaded files to the time the post was uploaded on *chan, is that what you mean?

Ah I'm dumb I was talking about the exif data creation date. Piwigo sorts using that but it seems like a hassle to do.

Do you know why the 8chan scraper broke?
I'm not sure what changed

**Comment by space-nuko** [comment]
It was because they changed the name of the cookie that validates you've clicked through their disclaimer, should be fixed in 3545995

**Comment by a-person-oops** [comment]
IGNORE ME JUST REALIZED YOU HAVE A SCRIPT :D
